services:
  db:
    image: postgres:17
    container_name: airport-db
    ports:
      - "5432:5432"
    env_file:
      - .env
  redis:
    image: redis:8
    container_name: airport-redis
    ports:
      - "6379:6379"
  web:
    build: .
    container_name: airport-drf
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    env_file:
      - .env
  celery:
    build: .
    command: celery -A airport worker --loglevel=info
    depends_on:
      - db
      - redis