# Generated by Django 6.0.5 on 2026-05-21 13:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('aviation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('ticket_status', models.CharField(choices=[('BKD', 'booked'), ('USE', 'used'), ('PAD', 'paid'), ('CND', 'cancelled')], default='BKD', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_time', models.DateTimeField()),
                ('arrival_time', models.DateTimeField()),
                ('flight_status', models.CharField(choices=[('SCH', 'scheduled'), ('BRG', 'boarding'), ('DEP', 'departed'), ('DLD', 'delayed'), ('CND', 'cancelled')], default='SCH', max_length=3)),
                ('airline_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='aviation.airline')),
                ('arrival_airport', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='arrivals', to='aviation.airport')),
                ('departure_airport', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='departures', to='aviation.airport')),
            ],
        ),
    ]
