# Generated by Django 6.0.5 on 2026-05-29 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aviation', '0006_fleetitem'),
        ('flights', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='airplane',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='aviation.fleetitem'),
        ),
    ]
