# Generated by Django 6.0.5 on 2026-05-26 14:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='ticket_price',
        ),
        migrations.AddField(
            model_name='flight',
            name='available_tickets',
            field=models.PositiveIntegerField(default=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='flight',
            name='flight_number',
            field=models.CharField(default='AA234', max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='flight',
            name='ticket_price',
            field=models.DecimalField(decimal_places=2, default=1000, max_digits=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticket',
            name='client',
            field=models.ForeignKey(default=123, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticket',
            name='flight_number',
            field=models.ForeignKey(default=213, on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='flights.flight'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticket',
            name='seat',
            field=models.CharField(default=328, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='flight',
            name='flight_status',
            field=models.CharField(choices=[('SCHEDULED', 'scheduled'), ('BOARDING', 'boarding'), ('DEPARTED', 'departed'), ('DELAYED', 'delayed'), ('CANCELLED', 'cancelled')], default='SCHEDULED', max_length=10),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticket_status',
            field=models.CharField(choices=[('BOOKED', 'booked'), ('USED', 'used'), ('PAID', 'paid'), ('CANCELLED', 'cancelled')], default='BOOKED', max_length=10),
        ),
    ]
