# Generated by Django 6.0.5 on 2026-05-28 11:32

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0002_remove_ticket_ticket_price_flight_available_tickets_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='client',
            new_name='passenger_name',
        ),
        migrations.RemoveField(
            model_name='flight',
            name='available_tickets',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='flight_number',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='seat',
        ),
        migrations.AddField(
            model_name='flight',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='AirplaneSeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row', models.PositiveIntegerField()),
                ('seat', models.PositiveIntegerField()),
                ('class_type', models.CharField(choices=[('PREMIUM', 'premium'), ('BASIC', 'basic')], default='BASIC', max_length=7)),
                ('status', models.CharField(choices=[('AVAILABLE', 'available'), ('RESERVED', 'reserved'), ('SOLD', 'sold')], default='AVAILABLE', max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('flight_number', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='flights.flight')),
            ],
            options={
                'unique_together': {('flight_number', 'row', 'seat')},
            },
        ),
        migrations.AddField(
            model_name='ticket',
            name='flight_seat',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='flights.airplaneseat'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PENDING', 'pending'), ('CONFIRMED', 'confirmed'), ('CANCELLED', 'cancelled')], default='PENDING', max_length=10)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='ticket',
            name='booking',
            field=models.ForeignKey(default=12, on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='flights.booking'),
            preserve_default=False,
        ),
    ]
