# Generated by Django 6.0.5 on 2026-06-01 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0002_alter_flight_airplane'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='ticket_coefficient',
            field=models.FloatField(default=1.2, max_length=5),
            preserve_default=False,
        ),
    ]
