# Generated by Django 6.0.5 on 2026-05-28 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aviation', '0004_remove_fleet_unique_airline_airplane_and_more'),
        ('flights', '0003_rename_client_ticket_passenger_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='airplane',
            field=models.ForeignKey(default=12, on_delete=django.db.models.deletion.PROTECT, to='aviation.airplane'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='airplaneseat',
            name='flight_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='seats', to='flights.flight'),
        ),
    ]
