# Generated by Django 6.0.5 on 2026-06-01 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aviation', '0009_alter_airplaneseat_class_type'),
        ('flights', '0003_flight_ticket_coefficient'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='ticket',
            name='unique_ticket',
        ),
        migrations.AlterField(
            model_name='ticket',
            name='flight_seat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aviation.airplaneseat'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticket_status',
            field=models.CharField(choices=[('AVAILABLE', 'available'), ('BOOKED', 'booked'), ('USED', 'used'), ('PAID', 'paid'), ('CANCELLED', 'cancelled')], default='AVAILABLE', max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='ticket',
            unique_together={('flight_number', 'flight_seat')},
        ),
    ]
