# Generated by Django 6.0.5 on 2026-06-01 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0005_alter_ticket_booking_alter_ticket_passenger_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flight',
            name='ticket_coefficient',
        ),
        migrations.AddField(
            model_name='flight',
            name='business_percent',
            field=models.PositiveIntegerField(default=10),
            preserve_default=False,
        ),
    ]
