# Generated by Django 6.0.5 on 2026-06-01 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0006_remove_flight_ticket_coefficient_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='user_id',
            new_name='user',
        ),
    ]
