# Generated by Django 6.0.5 on 2026-05-20 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Airlines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airline_name', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('airplane_capacity', models.PositiveIntegerField()),
                ('founded_year', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Airplanes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airplane_brand', models.CharField(max_length=50)),
                ('airplane_model', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Airports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airport_name', models.CharField(max_length=200)),
                ('iata_code', models.CharField(max_length=3, unique=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locations.cities')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locations.countries')),
            ],
        ),
        migrations.CreateModel(
            name='AirportsAirlines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airline_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aviation.airlines')),
                ('airport_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aviation.airports')),
            ],
        ),
        migrations.CreateModel(
            name='Fleets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fleet_size', models.PositiveIntegerField()),
                ('airline_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aviation.airlines')),
                ('airplane_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aviation.airplanes')),
            ],
        ),
    ]
