# Generated by Django 6.0.5 on 2026-05-21 09:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aviation', '0001_initial'),
        ('flights', '0001_initial'),
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Airplanes',
            new_name='Airplane',
        ),
        migrations.RenameModel(
            old_name='Fleets',
            new_name='Fleet',
        ),
        migrations.RemoveField(
            model_name='airports',
            name='city',
        ),
        migrations.RemoveField(
            model_name='airports',
            name='country',
        ),
        migrations.RemoveField(
            model_name='airportsairlines',
            name='airport_name',
        ),
        migrations.RemoveField(
            model_name='airportsairlines',
            name='airline_name',
        ),
        migrations.RenameModel(
            old_name='Airlines',
            new_name='Airline',
        ),
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airport_name', models.CharField(max_length=200)),
                ('iata_code', models.CharField(max_length=3, unique=True)),
                ('airline', models.ManyToManyField(related_name='airports', to='aviation.airline')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locations.city')),
            ],
        ),
    ]
