# Generated by Django 6.0.5 on 2026-05-26 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aviation', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='airline',
            old_name='airline_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='airplane',
            old_name='airplane_brand',
            new_name='brand',
        ),
        migrations.RenameField(
            model_name='airplane',
            old_name='airplane_model',
            new_name='model',
        ),
        migrations.RenameField(
            model_name='fleet',
            old_name='airline_name',
            new_name='airline',
        ),
        migrations.RenameField(
            model_name='fleet',
            old_name='airplane_name',
            new_name='airplane',
        ),
        migrations.RemoveField(
            model_name='airline',
            name='airplane_capacity',
        ),
        migrations.AddField(
            model_name='airplane',
            name='seats',
            field=models.PositiveIntegerField(default=100),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='airplane',
            constraint=models.UniqueConstraint(fields=('brand', 'model'), name='unique_brand_model'),
        ),
        migrations.AddConstraint(
            model_name='fleet',
            constraint=models.UniqueConstraint(fields=('airline', 'airplane'), name='unique_airline_airplane'),
        ),
    ]
