# Generated by Django 6.0.5 on 2026-05-21 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aviation', '0002_rename_airplanes_airplane_rename_fleets_fleet_and_more'),
        ('flights', '0002_rename_tickets_ticket_alter_flight_arrival_airport_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Airports',
        ),
        migrations.DeleteModel(
            name='AirportsAirlines',
        ),
    ]
