# Generated by Django 6.0.5 on 2026-05-28 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aviation', '0002_rename_airline_name_airline_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='airplane',
            old_name='seats',
            new_name='rows',
        ),
        migrations.AddField(
            model_name='airplane',
            name='seats_per_row',
            field=models.PositiveIntegerField(default=100),
            preserve_default=False,
        ),
    ]
