# Generated by Django 6.0.5 on 2026-05-28 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aviation', '0003_rename_seats_airplane_rows_airplane_seats_per_row'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='fleet',
            name='unique_airline_airplane',
        ),
        migrations.RenameField(
            model_name='airport',
            old_name='airport_name',
            new_name='name',
        ),
        migrations.DeleteModel(
            name='Fleet',
        ),
    ]
