# Generated by Django 6.0.5 on 2026-05-29 09:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aviation', '0004_remove_fleet_unique_airline_airplane_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AirplaneSeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row', models.PositiveIntegerField()),
                ('seat', models.PositiveIntegerField()),
                ('class_type', models.CharField(choices=[('PREMIUM', 'premium'), ('BASIC', 'basic')], default='BASIC', max_length=7)),
                ('airplane', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='airplane', to='aviation.airplane')),
            ],
        ),
    ]
