# Generated by Django 6.0.5 on 2026-05-29 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aviation', '0005_airplaneseat'),
    ]

    operations = [
        migrations.CreateModel(
            name='FleetItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tail_number', models.CharField(max_length=8, unique=True)),
                ('airline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aviation.airline')),
                ('airplane', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aviation.airplane')),
            ],
        ),
    ]
