# Generated by Django 6.0.5 on 2026-05-29 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aviation', '0006_fleetitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airplaneseat',
            name='seat',
            field=models.CharField(),
        ),
    ]
