# Generated by Django 6.0.5 on 2026-05-29 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aviation', '0007_alter_airplaneseat_seat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airplaneseat',
            name='seat',
            field=models.CharField(max_length=10),
        ),
    ]
