# Generated by Django 6.0.5 on 2026-05-29 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aviation', '0008_alter_airplaneseat_seat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airplaneseat',
            name='class_type',
            field=models.CharField(choices=[('BUSINESS', 'business'), ('ECONOMY', 'economy')], default='ECONOMY', max_length=10),
        ),
    ]
