# Generated by Django 6.0.5 on 2026-06-01 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aviation', '0009_alter_airplaneseat_class_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='airplane',
            name='business_rows_percent',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
