# Generated by Django 6.0.5 on 2026-05-21 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aviation', '0002_rename_airplanes_airplane_rename_fleets_fleet_and_more'),
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cities',
            new_name='City',
        ),
        migrations.RenameModel(
            old_name='Countries',
            new_name='Country',
        ),
    ]
